version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile 
    image: collection-scheduling-api:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
