name: .NET Core CI

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore "CollectionSchedulingAPI/CollectionSchedulingAPI.csproj"

    - name: Build project
      run: dotnet build "CollectionSchedulingAPI/CollectionSchedulingAPI.csproj" --configuration Release --no-restore

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Run tests
      run: dotnet test "CollectionSchedulingAPI/CollectionSchedulingAPI.csproj" --no-build --verbosity normal
